### ISSUE TITLE
Crash when changing the display size

### ISSUE THREAD

**Issue by blazer30** [Ruin0x11/ElonaPlusCustom_GX#19]
Got the same error message as from my last issue.
Restarting the computer won't fix the issue either.

**Comment by Ruin0x11** [comment]
Is there an `error.txt` file in the game directory I could take a look at? From what I understand changes to the resolution should only take place when the game is restarted. Was there anything specific you were doing in-game?

**Comment by blazer30** [comment]
I don't see any. I load up my save at 1920X1080 res and that error #1 message shows up and crashes.

**Comment by blazer30** [comment]
Half the resolution options crash the game for me. It works for the rest. Progress. Some resolution options don't increment, so I have about three or four redundant ones.

**Comment by Ruin0x11** [comment]
Should be fixed in [2.07.1.0](https://github.com/Ruin0x11/ElonaPlusCustom-GX/releases/tag/2.07.1.0). Could you try it and see?

**Comment by tarunio** [comment]
New crash when using 800x600 fullscreen and changing screen display to 800x600.
version 2.07.1.0.

**Comment by Ruin0x11** [comment]
Could you try this build? There were a couple of resolution-related bugs from 2.07.1.0 I'm trying to fix.

[elonapluscgx.exe](https://mega.nz/file/Q3BmHDLS#dn3Qna2tpSENFcSBQDa84lRfpo6ZkclqBsdCX7OWScI)

Also, one other thing to note is that the game won't go into "true" fullscreen unless the post-DPI-multiplied resolution matches one of the resolutions supported by your display. Those resolutions are the ones displayed in the options menu. For resolutions like 1280x720 upscaled by 1.5 to 1920x1080, the fullscreen would work if 1080p is one of the (non-scaled) resolutions in the list.

**Comment by tarunio** [comment]
nice its not crashing from the .exe you posted.

**Comment by Ruin0x11** [comment]
Okay, this should be fixed (for real this time) in [2.07.1.1](https://github.com/Ruin0x11/ElonaPlusCustom-GX/releases/tag/2.07.1.1). If not then please do reopen the issue again.

**Comment by blazer30** [comment]
I am still getting the same crashes on the larger resolution options and even changing the DPI for them.
